-- Valdória — seed do catálogo (52 cartas). Gerado do index.html.
insert into public.cards (slug,nome,elemento,raridade,custo,atk,def,especial,ordem) values
  ('recruta-da-forja','Recruta da Forja','fogo','comum',1,2,1,'"Só marreta e teimosia."',0),
  ('cao-de-brasa','Cão de Brasa','fogo','comum',2,4,2,'"Late fogo e corre atrás do próprio rabo."',1),
  ('escudeiro-de-cobre','Escudeiro de Cobre','fogo','comum',1,1,3,'"Segura esse escudo o dia inteiro."',2),
  ('faisca-travessa','Faísca Travessa','fogo','comum',1,2,1,'"Solta faísca e foge rindo."',3),
  ('lanceiro-flamejante','Lanceiro Flamejante','fogo','comum',2,3,2,'"A lança pega fogo, o talento ficou na forja."',4),
  ('sacerdote-das-brasas','Sacerdote das Brasas','fogo','comum',2,2,2,'"Reza pras brasas. Ninguém respondeu."',5),
  ('gladiadora-ember','Gladiadora Ember','fogo','incomum',2,3,2,'Sede de arena — ao atacar, +2 ATK se o oponente tiver 10 ou menos de Vida.',6),
  ('berserker-cinzas','Berserker Cinzas','fogo','incomum',2,3,2,'Fúria cega — ao atacar, +3 ATK, mas você perde 1 de Vida.',7),
  ('salamandra-de-guerra','Salamandra de Guerra','fogo','incomum',3,4,3,'Pele de lava — ao defender, +2 DEFESA.',8),
  ('piromante-vingativa','Piromante Vingativa','fogo','incomum',3,3,3,'Chama vingativa — se você perder Vida neste confronto, o oponente também perde 1.',9),
  ('ignarok-o-incandescente','Ignarok, o Incandescente','fogo','rara',3,4,3,'Investida ígnea — ao atacar, ignora 2 de DEFESA do inimigo.',10),
  ('fenix-de-chamalar','Fênix de Chamalar','fogo','rara',4,4,4,'Renascer — ao vencer o confronto, você recupera 3 de Vida.',11),
  ('vulkanor-senhor-das-forjas','Vulkanor, Senhor das Forjas','fogo','epica',4,5,4,'Ira do Vulcão — ao atacar, ignora TODA a DEFESA do inimigo.',12),
  ('grumete-das-mares','Grumete das Marés','agua','comum',1,1,2,'"Ainda tá aprendendo a dar nó."',13),
  ('caranguejo-couracado','Caranguejo Couraçado','agua','comum',2,2,4,'"Anda de lado e não larga a casca."',14),
  ('sereia-cantora','Sereia Cantora','agua','comum',2,2,2,'"Canta bonito, encanta marujo."',15),
  ('baiacu-explosivo','Baiacu Explosivo','agua','comum',1,2,1,'"Incha, faz cara feia e... só isso."',16),
  ('pescador-teimoso','Pescador Teimoso','agua','comum',2,3,2,'"Jura que um dia fisga algo especial. Hoje não."',17),
  ('golfinho-batedor','Golfinho Batedor','agua','comum',1,2,1,'"Poder especial? Só o carisma."',18),
  ('sanguessuga-abissal','Sanguessuga Abissal','agua','incomum',2,3,2,'Vampirismo — se causar dano ao atacar, você recupera 1 de Vida.',19),
  ('corsaria-das-brumas','Corsária das Brumas','agua','incomum',3,4,2,'Névoa — ao defender, o atacante não recebe bônus elemental neste confronto.',20),
  ('curandeira-da-mare','Curandeira da Maré','agua','incomum',3,2,4,'Bênção das águas — ao fim do confronto, você recupera 1 de Vida.',21),
  ('guardia-do-recife','Guardiã do Recife','agua','incomum',3,2,5,'Barreira de coral — ao defender, +3 DEFESA.',22),
  ('almirante-neritide','Almirante Neritide','agua','rara',4,4,4,'Contra-maré — ao defender, se o ataque falhar, você recupera 2 de Vida.',23),
  ('leviata-das-profundezas','Leviatã das Profundezas','agua','rara',4,5,3,'Esmagar — ao atacar, ignora 3 de DEFESA do inimigo.',24),
  ('thalassa-rainha-das-mares','Thalassa, Rainha das Marés','agua','epica',4,4,5,'Maré Suprema — ao defender, +2 DEFESA; se o ataque falhar, +3 de Vida.',25),
  ('broto-voraz','Broto Voraz','nat','comum',1,1,2,'"Especial? Quem sabe quando crescer."',26),
  ('filhote-de-lobo','Filhote de Lobo','nat','comum',1,2,1,'"Morde o próprio rabo e dorme."',27),
  ('casca-grossa','Casca-Grossa','nat','comum',2,2,4,'"Dura como tronco, lenta como tronco."',28),
  ('espinho-saltitante','Espinho Saltitante','nat','comum',1,1,2,'"Espeta quem chega perto sem querer."',29),
  ('druida-aprendiz','Druida Aprendiz','nat','comum',2,2,2,'"Ainda decorando o primeiro feitiço."',30),
  ('javali-furioso','Javali Furioso','nat','comum',2,4,1,'"Corre reto e grita. Estratégia? Não."',31),
  ('alcateia-unida','Alcateia Unida','nat','incomum',2,2,2,'Matilha — +1 ATK para cada outra carta de Natureza na sua mão.',32),
  ('guardiao-do-arco-iris','Guardião do Arco-Íris','nat','incomum',3,3,3,'Biodiversidade — 3+ elementos na mão: +2 ATK e +2 DEFESA.',33),
  ('urso-espirito','Urso Espírito','nat','incomum',3,4,3,'Fúria selvagem — +1 ATK ao atacar e +1 DEFESA ao defender.',34),
  ('ent-anciao','Ent Ancião','nat','incomum',3,3,4,'Raízes — ao defender, +3 DEFESA.',35),
  ('colosso-de-carvalho','Colosso de Carvalho','nat','rara',3,3,4,'Casca imortal — ao defender, se o ataque falhar, o recuo é dobrado.',36),
  ('matriarca-da-floresta','Matriarca da Floresta','nat','rara',4,3,5,'Elo da matilha — +1 ATK e +1 DEFESA por carta de Natureza na sua mão.',37),
  ('gaia-a-mae-bosque','Gaia, a Mãe-Bosque','nat','epica',4,4,4,'Despertar da Selva — na mão, suas cartas de Natureza têm +1/+1.',38),
  ('fagulha-eletrica','Fagulha Elétrica','raio','comum',1,2,1,'"Solta um tique de choque e se acha."',39),
  ('vaga-lume-estatico','Vaga-lume Estático','raio','comum',1,1,2,'"Pisca bonito. Poder de batalha, nenhum."',40),
  ('sentinela-de-cobre','Sentinela de Cobre','raio','comum',2,2,3,'"Fica parado conduzindo faísca."',41),
  ('duende-faisca','Duende Faísca','raio','comum',1,2,1,'"Curto-circuito por diversão. Útil? Nunca."',42),
  ('arqueiro-do-pico','Arqueiro do Pico','raio','comum',2,3,2,'"Mira, atira, erra às vezes."',43),
  ('corredor-do-vento','Corredor do Vento','raio','comum',2,3,1,'"Corre rápido, pensa devagar."',44),
  ('aguia-trovejante','Águia Trovejante','raio','incomum',2,3,2,'Ataque relâmpago — ao atacar, ignora 1 de DEFESA do inimigo.',45),
  ('condutor-temerario','Condutor Temerário','raio','incomum',2,4,1,'Sobrecarga — ao atacar, +3 ATK; se falhar, você perde 1 de Vida extra.',46),
  ('cavaleira-do-trovao','Cavaleira do Trovão','raio','incomum',3,4,2,'Ímpeto do trovão — ao atacar, se vencer, o oponente perde +1 de Vida.',47),
  ('xama-das-tempestades','Xamã das Tempestades','raio','incomum',3,3,3,'Corrente — ao atacar com vantagem elemental, o bônus é +4.',48),
  ('senhor-dos-ventos','Senhor dos Ventos','raio','rara',3,3,3,'Reflexos do raio — ao defender, reduz em 2 o dano sofrido.',49),
  ('tempestade-viva','Tempestade Viva','raio','rara',4,4,4,'Descarga — ao atacar, +2 ATK e ignora 2 de DEFESA do inimigo.',50),
  ('zephyros-furia-do-ceu','Zephyros, Fúria do Céu','raio','epica',4,5,3,'Julgamento Relâmpago — ao atacar, +3 ATK e nunca sofre recuo.',51)
on conflict (slug) do update set
  nome=excluded.nome, elemento=excluded.elemento, raridade=excluded.raridade,
  custo=excluded.custo, atk=excluded.atk, def=excluded.def, especial=excluded.especial, ordem=excluded.ordem;
